---
layout: default
title: 16. 비동기처리
parent: JS
nav_order: 16
---

## #16. 비동기처리
<img src="/assets/images/css/비동기1.png" >
<pre>
function work() {
  const start = Date.now();
  for (let i = 0; i < 1000000000; i++) {}
  const end = Date.now();
  console.log(end - start + 'ms');
}

work();
console.log('다음 작업');
</pre>
-> 동기적(Synchronous) :  work()함수가 호출되면 for문이 다 돌아갈 때까지 다른 작업을 처리하지 않고 for문만 실행

<img src="/assets/images/css/비동기2.png" > 


<img src="/assets/images/css/function1.png" >비동식 형태로 전환하고 싶다면… =>setTimeout 함수 사용
<pre>
function work() {
  <b style="color:black; background:yellow;">setTimeout(()</b> => {
    const start = Date.now();
    for (let i = 0; i < 1000000000; i++) {}
    const end = Date.now();
    console.log(end - start + 'ms');
  }, 0);
}

console.log('작업 시작!');
work();
console.log('다음 작업');
</pre>
-> setTimeout 함수는 첫번째 파라미터에 넣는 함수를 두번째 파라미터에 넣은 시간(ms 단위)이 흐른 후 호출.<br>
-> 여기서는 두번째 파라미터에 0을 넣음 => 이 함수는 바로 실행<br>
&nbsp;&nbsp;&nbsp; => 0ms이후에 실행한다는 의미이지만 실제로는 4ms 이후에 실행<br>
-> <b style="color:red;">setTimeout을 사용하면 우리가 정한 작업이 백그라운드에서 수행되기 때문에 기존의 코드 흐름을 막지 않고 동시에 다른 작업들을 진행 할 수 있음</b><

<img src="/assets/images/css/비동기3.png" > 
-> <b style="color:red;">결과물을 보면, 작업이 시작 되고 나서, for 루프가 돌아가는 동안 다음 작업도 실행되고, for 루프가 끝나고 나서 몇 ms 걸렸는지 나타나고 있음.</b>

<img src="/assets/images/css/function1.png" ><b style="background:yellow;">Work() 함수가 끝난 다음에 어떤 작업을 처리하고 싶을 경우
		-> 콜백 함수를 파라미터로 전달</b>

<b style="color:blue;">★ 콜백 함수란? (비동기적 함수1)
 - 함수 타입의 값을 파라미터로 넘겨줘서, 파라미터로 받은 함수를 특정 작업이 끝나고 호출을 해주는 것을 의미</b>

<pre>
function work(callback) {
  setTimeout(() => {
    const start = Date.now();
    for (let i = 0; i < 1000000000; i++) {}
    const end = Date.now();
    console.log(end - start + 'ms');
    callback();
  }, 0);
}

console.log('작업 시작!');
work(() => {
  console.log('작업이 끝났어요!')
});
console.log('다음 작업');
</pre>
<b style="color:blue;">
★ 비동기적으로 처리하게 되는 작업들

1. Ajax Web API 요청 : 만약 서버쪽에서 데이터를 받아와야 할 때는, 요청을 하고 서버에서 응답을 할 때까지 대기를 해야 되기 때문에 작업을 비동기적으로 처리

2. 파일 읽기 : 주로 서버 쪽에서 파일을 읽어야 하는 상황에는 비동기적으로 처리
3. 암호화/ 복호화 : 암호화/ 복호화를 할 때에도 바로 처리가 되지 않고, 시간이 어느정도 걸리는 경우가 있기 때문에 비동기적으로 처리

4. 작업 예약 : 단순히 어떤 작업을 몇초 후에 스케쥴링 해야 하는 상황에는, setTimeout 을 사용하여 비동기적으로 처리
</b>

<b style="color:blue;">
★ Promise (비동기적 함수2)</b>

- 비동기 작업을 조금 더 편하게 처리 하는 함수, 콜백 함수로 처리를 하게 된다면 비동기 작업이 많아질 경우 코드가 쉽게 난잡해지게 됨.
- <b style="color:red;">Promise를 사용하면 이렇게 코드의 깊이가 깊어지는 현상을 방지</b>

### promise 만들기
- <b style="color:red;">promise는 성공 할 수도 있고, 실패 할 수도 있음.
- 성공 할 때에는 resolve를 호출, 실패할 때는 reject를 호출
- reject 는 사용되지 않으면 생략 가능</b>

Ex) 1초 뒤에 성공시키는 상황
<pre>
const myPromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(1);
  }, 1000);
});

myPromise.then(n => {
  console.log(n);
});
</pre>
-> <b style="color:red;">resolve를 호출 할 때 특정 값을 파라미터로 넣어주면, 이 값을 작업이 끝나고 나서 사용할 수 있음.<br>
-> 작업이 끝나고 나서 또 다른 작업을 해야 할 때에는 Promise뒤에 .<b style="background:yellow;">them(…)</b>을 붙여서 사용</b>
 
<img src="/assets/images/css/비동기4.png" > 

Ex) 1초 뒤에 실패시키는 상황
<pre>
const myPromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error());
  }, 1000);
});

myPromise
  .then(n => {
    console.log(n);
  })
  .catch(error => {
    console.log(error);
  });
</pre>
-> <b style="color:red;">실패하는 상황에서는 reject를 사용, .catch를 통하여 실패했을시 수행 할 작업 설정 가능</b>
 
<img src="/assets/images/css/비동기5.png" > 

=> Promise를 만드는 함수
<pre>
function increaseAndPrint(n) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const value = n + 1;
      if (value === 5) {	 <b style="color:red;">// n값이 5가 될때까지 반복, 5일경우 에러 return</b>
        const error = new Error();
        error.name = 'ValueIsFiveError';	<b style="color:red;">//에러일 경우 반환 메세지 설정</b>
        reject(error);	<b style="color:red;">//에러일 경우 메세지 반환</b>
        return;
      }
      console.log(value);
      resolve(value);	<b style="color:red;">//성공시 value 값 반환</b>
    }, 1000);
  });
}

increaseAndPrint(0).then((n) => {
  console.log('result: ', n);
})
</pre>

<img src="/assets/images/css/비동기6.png" > 

<img src="/assets/images/css/function1.png" >Promise의 속성 중, then 내부에 넣은 함수를 또 Promise를 리턴하게 된다면, 연달아 사용 가능
<pre>
function increaseAndPrint(n) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const value = n + 1;
      if (value === 5) {
        const error = new Error();
        error.name = 'ValueIsFiveError';
        reject(error);
        return;
      }
      console.log(value);
      resolve(value);
    }, 1000);
  });
}

increaseAndPrint(0)
  .then(n => {
    return increaseAndPrint(n);
  })
  .then(n => {
    return increaseAndPrint(n);
  })
  .then(n => {
    return increaseAndPrint(n);
  })
  .then(n => {
    return increaseAndPrint(n);
  })
  .then(n => {
    return increaseAndPrint(n);
  })
  .catch(e => {			<b style="color:red;">//catch는 에러가 발생했을 때 특정 작업을 하기 위함</b>
    console.error(e);		
  });
  </pre>

 <img src="/assets/images/css/비동기7.png" > 

<b style="color:red;">-> catch를 사용하고 안하고는 콘솔에 출력되는 결과가 다름<br>
-> catch는 에러가 발생했을 때 특정 작업을 하기 위함<br>
-> catch를 안했을 경우 “Uncaught (in promise) ValuelsFiveError” – ValuelsFiveError가 잡히지 X<br>
-> catch를 했을 경우 “ValuelsFiveError”라고 나타남</b>

<img src="/assets/images/css/function1.png" >위의 코드를 간단히 정리한 결과
<pre>
function increaseAndPrint(n) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const value = n + 1;
      if (value === 5) {
        const error = new Error();
        error.name = 'ValueIsFiveError';
        reject(error);
        return;
      }
      console.log(value);
      resolve(value);
    }, 1000);
  });
}

increaseAndPrint(0)
  <b style="color:red; background:yellow;">.then(increaseAndPrint)</b>
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .catch(e => {
    console.error(e);
  });
</pre>

<b style="color:red; background:yellow;">-> increaseAndPring(0)의 결과 1을 .then의 파라미터 n으로 받아와서 다시 increaseAndPrint를 호출<br>
-> .then에서 Promise를 반환하면 .then을 다시 연달아서 사용 가능</b><br>
-> Promise를 사용하면, 비동기 작업의 개수가 많아져도 코드의 깊이가 깊어지지 X<br>
<b style="color:red;">-> but, 에러를 잡을 때 몇번째에서 발생했는지 알아내기 어렵고, 특정 조건에 따라 분기를 나누는 작업도 어렵고, 특정 값을 공유해가면서 작업을 처리하기 까다로움<br>
  => 그래서 async/await 를 사용</b>

<b style="color:blue;">★ async/await (비동기적 함수3)</b>
- Promise를 더욱 쉽게 사용 할 수 있게 해줌
<pre>
function <b style="color:black; background:#00fffa;">sleep(ms)</b> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

<b style="color:black; background:yellow;">async</b> function process() {
  console.log('안녕하세요!');
  <b style="color:black; background:yellow;">await</b> <b style="color:black; background:#00fffa;">sleep(1000)</b>; // 1초쉬고
  console.log('반갑습니다!');
}

process();
</pre>

<img src="/assets/images/css/비동기8.png" > 

-> async/await 문법을 사용할 때에는, <b style="color:red;">함수를 선언 할 때 함수의 앞부분에 async 키워드를 붙임</b><br>
&nbsp;&nbsp;&nbsp;그리고 <b style="color:red;">Promise 앞부분에 await를 넣어주면 해당 Promise가 끝날때까지 기다렸다가 다음 작업을 수행 할 수 있음</b><br>
-> 위의 코드는 sleep이라는 함수를 만들어서 파라미터로 넣어준 시간 만큼 기다리는 Promise를 만들고 이를 Process 함수에서 사용<br>
-> <b style="color:red; background:yellow;">함수에서 async를 사용하면, 해당 함수는 결과값으로 Promise를 반환</b>
<pre>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function process() {
  console.log('안녕하세요!');
  await sleep(1000); // 1초쉬고
  console.log('반갑습니다!');
}

process().then(() => {	<b style="color:red;">//process()함수가 끝난 뒤에 실행</b>
  console.log('작업이 끝났어요!');
});
</pre> 

<img src="/assets/images/css/비동기9.png" > 

<b style="color:red;">* async 함수에서 에러를 발생 시킬때에는 throw를 사용하고, 에러를 잡아낼 때에는 try/catch 문을 사용</b>
<pre>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function makeError() {
  await sleep(1000);
  const error = new Error();
  throw error;	<b style="color:red;">//throw : 에러 발생</b>
}

async function process() {
  try {		<b style="color:red;">//try…catch : 에러를 잡아낼 때 사용</b>
    await makeError();
  } catch (e) {
    console.error(e);
  }
}

process();
</pre>
 
<img src="/assets/images/css/비동기10.png" > 

Ex1) 여러개의 비동기 함수
<pre>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};
const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

async function process() {
  const dog = await getDog();
  console.log(dog);
  const rabbit = await getRabbit();
  console.log(rabbit);
  const turtle = await getTurtle();
  console.log(turtle);
}

process();
</pre>
<img src="/assets/images/css/비동기11.png" > 

-> getDog 는 1초, getRabbit 는 0.5초, getTurtle 은 3초 걸림<br>
-> process 함수에서 연달아서 사용하게 되면서, process 함수가 실행되는 총 시간은 4.5초

Ex2) <b style="color:blue;">getDog -> getRabbit -> getTurtle 순서대로 실행되는 것을 동시에 작업하고 싶을 경우</b>
     Promise.all 을 사용
<pre>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};
const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

<b style="color:red;">async function process() {
  const results = await <b style="background:yellow;">Promise.all([getDog(), getRabbit(), getTurtle()]);</b>
  console.log(results);
}</b>

process();
</pre>

<img src="/assets/images/css/비동기12.png" >  

<img src="/assets/images/css/function1.png" >비구조화 할당 문법으로 사용 -> 각 결과값을 따로 따로 추출해서 조회

<pre>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};
const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};
<b style="color:red;">
async function process() {
  const [dog, rabbit, turtle] = await <b style="background:yellow;">Promise.all</b>([
    getDog(),
    getRabbit(),
    getTurtle()
  ]);
  console.log(dog);
  console.log(rabbit);
  console.log(turtle);
}
</b>
process();
</pre>

-> <b style="color:red;">Promise.all를 사용 할 때에는, 등록한 프로미스 중 하나라도 실패하면, 모든게 실패 한 것으로 간주!</b>

Ex3) <b style="color:blue;">Promise.race : 여러개의 Promise를 등록해서 실행했을 때 가장 빨리 끝난것 하나만의 결과값을 가져옴</b>
<pre>
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};
const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

<b style="color:red;">
async function process() {
  const first = await <b style="background:yellow;">Promise.race</b>([
    getDog(),
    getRabbit(),
    getTurtle()
  ]);
  console.log(first);
}
</b>
process();
</pre>
<img src="/assets/images/css/비동기13.png" > 

-> <b style="color:red;">Promise.race 는 가장 다른 Promise가 먼저 성공하기 전에 가장 먼저 끝난 Promise가 실패하면 실패로 간주.
-> 따라서, 위의 코드에서 getRabbit 에서 에러를 발생시킨다면 에러를 잡아낼 수 있지만, getTurtle 이나 getDog 에서 발생한 에러는 무시됨</b>
